<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<DebugType>portable</DebugType>
		<OutputPath>./bin</OutputPath>
		<Deterministic>False</Deterministic>
	</PropertyGroup>

  <Target Name="ReadModVersion" BeforeTargets="GetAssemblyVersion">
    <ReadLinesFromFile File="$(MSBuildProjectDirectory)\mod_meta.json">
      <Output TaskParameter="Lines" ItemName="ModMetaLines" />
    </ReadLinesFromFile>

    <PropertyGroup>
      <ModMetaJson>@(ModMetaLines, '')</ModMetaJson>
      <Version>$([System.Text.RegularExpressions.Regex]::Match('$(ModMetaJson)', '&quot;Version&quot;\s*:\s*&quot;([^&quot;]+)&quot;').Groups[1].Value)</Version>
    </PropertyGroup>
  </Target>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\WinchCommon\WinchCommon.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		</ProjectReference>
		<ProjectReference Include="..\..\Winch\Winch.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="ExampleItems.csproj.user" />
		<None Include="Assets\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="default_config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="mod_meta.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
