name: Build artifacts and draft release

env:
    PROJ_NAME: Winch
    MODS_DIR: Winch.Examples
    DISASTER_BUTTON: DisasterButton
    EXAMPLE_ITEMS: ExampleItems
    INTRO_SKIPPER: IntroSkipper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
        version:
            description: Semver
            type: string

jobs:
  build:
    name: Create artifacts
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: "actions/checkout@v3"

        - name: Setup .NET
          uses: "actions/setup-dotnet@v3"

        - name: Build Winch
          run: dotnet build -c Debug

        - name: Check
          run: ls

        - name: Upload Winch Artifact
          uses: "actions/upload-artifact@v3"
          with:
            name: "${{ env.PROJ_NAME }}"
            path: "${{ env.PROJ_NAME }}/bin"
            
        - name: Upload DisasterButton Artifact
          uses: "actions/upload-artifact@v3"
          with:
            name: "${{ env.DISASTER_BUTTON }}"
            path: "${{ env.MODS_DIR }}/${{ env.DISASTER_BUTTON }}/bin"

        - name: Upload ExampleItems Artifact
          uses: "actions/upload-artifact@v3"
          with:
            name: "${{ env.EXAMPLE_ITEMS }}"
            path: "${{ env.MODS_DIR }}/${{ env.EXAMPLE_ITEMS }}/bin"
            
        - name: Upload IntroSkipper Artifact
          uses: "actions/upload-artifact@v3"
          with:
            name: "${{ env.INTRO_SKIPPER }}"
            path: "${{ env.MODS_DIR }}/${{ env.INTRO_SKIPPER }}/bin"
  release:
    name: Draft release
    if: ${{ vars.GITHUB_EVENT_NAME}} == "workflow_dispatch"
    runs-on: windows-latest
    needs: build
    steps:
        - name: Zip For Release
          run: |
            7z a ${{ env.PROJ_NAME }}.zip ${{ env.PROJ_NAME }}/bin/**
            7z a ${{ env.DISASTER_BUTTON }}.zip ${{ env.MODS_DIR }}/${{ env.DISASTER_BUTTON }}/bin/**
            7z a ${{ env.EXAMPLE_ITEMS }}.zip ${{ env.MODS_DIR }}/${{ env.EXAMPLE_ITEMS }}/bin/**
            7z a ${{ env.INTRO_SKIPPER }}.zip ${{ env.MODS_DIR }}/${{ env.INTRO_SKIPPER }}/bin/**

        - name: Create Release
          uses: "ncipollo/release-action@v1"
          with:
            allowUpdates: true
            commit: ${{ github.ref_name }}
            tag: v${{ inputs.version }}
            name: Version ${{ inputs.version }}
            omitBodyDuringUpdate: true
            artifacts: "${{ env.PROJ_NAME }}.zip ${{ env.DISASTER_BUTTON }}.zip ${{ env.EXAMPLE_ITEMS }}.zip ${{ env.INTRO_SKIPPER }}.zip"
            draft: true
    
      
