name: Build artifacts

on:
  workflow_call:
    inputs:
      build_type:
        description: 'Build type to pass to dotnet, should be either "Debug" or "Release"'
        required: false
        default: "Debug"
        type: string

jobs:
  build:
    name: Create artifacts
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup .NET
          uses: actions/setup-dotnet@v3

        - name: Build Winch
          run: dotnet build -c ${{ inputs.build_type }}

        - name: Check
          run: ls

        - name: Upload Winch Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Winch
            path: Winch/bin
            
        - name: Move Example Mods
          run: |
            for mod in DisasterButton ExampleItems IntroSkipper
            do
              mv Winch.Examples/$mod/bin/* Winch.Examples/$mod/
            done
            
        - name: Upload Example Mod Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Winch Examples
            path: |
                Winch.Examples/DisasterButton
                Winch.Examples/ExampleItems
                Winch.Examples/IntroSkipper
